In [48]:
import pandas as pd
import numpy as np
#import seaborn
import sklearn as skl
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import GradientBoostingRegressor
import matplotlib.pyplot as plt
from sklearn.metrics.scorer import make_scorer
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
#import future
#from autograd import grad
%matplotlib inline

In [49]:
demand_pred=pd.read_csv('demand_pred.csv')
demand_act=pd.read_csv('demand.csv')
price_pred=pd.read_csv('price_pred.csv')
price_act=pd.read_csv('price.csv')
solar_pred=pd.read_csv('solar_pred.csv')
solar_act=pd.read_csv('solar.csv')
lb_demand=pd.read_csv('Data_TestSet_PrivateEvaluation/Demand_Test_pred.csv', header=None)
lb_price=pd.read_csv('Data_TestSet_PrivateEvaluation/Price_Test_pred.csv', header=None)
lb_solar=pd.read_csv('Data_TestSet_PrivateEvaluation/Solar_Test_pred.csv', header=None)

In [50]:
price_pred_train=price_pred[:-50]  
price_pred_test=price_pred[-50:]
price_act_train= price_act[:-50]
price_act_test=price_act[-50:]

solar_pred_train=solar_pred[:-50]
solar_pred_test=solar_pred[-50:]
solar_act_train =solar_act[:-50]
solar_act_test=solar_act[-50:]

demand_pred_train=demand_pred[:-50]
demand_pred_test=demand_pred[-50:]
demand_act_train=demand_act[:-50]
demand_act_test=demand_act[-50:]



In [51]:
#lin reg by passing all 24 value in a day as feature and outputting 24 values
est = linear_model.LinearRegression()

est.fit(demand_pred,demand_act)
demandL24=est.predict(lb_demand)

est.fit(price_pred,price_act)
priceL24=est.predict(lb_price)

est.fit(solar_pred,solar_act)
solarL24=est.predict(lb_solar)

In [52]:
type(lb_solar)

pandas.core.frame.DataFrame

In [53]:
from sklearn import neighbors

In [54]:
#KNN using 24 features at once

estKnn24 = neighbors.KNeighborsRegressor(n_neighbors=7, n_jobs=-1)
estKnn24.fit(demand_pred, demand_act)
demandKnn24 = estKnn24.predict(lb_demand)

estKnn24 = neighbors.KNeighborsRegressor(n_neighbors=5, n_jobs=-1)
estKnn24.fit(price_pred, price_act)
priceKnn24 = estKnn24.predict(lb_price)

estKnn24 = neighbors.KNeighborsRegressor(n_neighbors=7, n_jobs=-1)
estKnn24.fit(solar_pred, solar_act)
solarKnn24 = estKnn24.predict(lb_solar)

print("done4")
#score2(pd.DataFrame(demandKnn24), pd.DataFrame(priceKnn24), pd.DataFrame(solarKnn24), np.concatenate( (demand_act_test,price_act_test,solar_act_test), axis=1) )

done4


In [55]:
#Elasticnet using 1 feature
estEN = linear_model.ElasticNetCV(cv=18)

#est.fit(np.array(demand_pred).reshape(-1,1), np.array(demand_act).ravel())
#scores=cross_val_score(estEN, np.array(demand_pred).reshape(-1,1), np.array(demand_act).ravel() )
#print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
estEN.fit( np.array(demand_pred).reshape(-1,1), np.array(demand_act).ravel() )
demandEN = estEN.predict(np.array(lb_demand).reshape(-1,1))

''' 
#scores=cross_val_score(estEN, np.array(price_pred).reshape(-1,1), np.array(price_act).ravel() )
#print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
estEN.fit( np.array(price_pred).reshape(-1,1), np.array(price_act).ravel())
priceEN = estEN.predict(np.array(lb_price).reshape(-1,1))

#scores=cross_val_score(estEN, np.array(solar_pred).reshape(-1,1), np.array(solar_act).ravel() )
#print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
estEN.fit( np.array(solar_pred).reshape(-1,1), np.array(solar_act).ravel()) 
solarEN = estEN.predict(np.array(lb_solar).reshape(-1,1))
''' 
print("done3")
#print(str(pd.DataFrame(demandEN).shape)+"s ")

#score3(pd.DataFrame(demandEN.reshape(50,24)), pd.DataFrame(priceEN.reshape(50,24)), pd.DataFrame(solarEN.reshape(50,24)), (demand_act_test), (price_act_test), (solar_act_test) )

done3


In [ ]:
0.96734275],[ 1.63682223]
0.96745217],[ 1.63512839
        
1.02092761],[ 1.64126239
 0.99368733],[ 1.6376168

In [56]:
estEN.set_params()

ElasticNetCV(alphas=None, copy_X=True, cv=18, eps=0.001, fit_intercept=True,
       l1_ratio=0.5, max_iter=1000, n_alphas=100, n_jobs=1,
       normalize=False, positive=False, precompute='auto',
       random_state=None, selection='cyclic', tol=0.0001, verbose=0)

In [57]:
''' 
def lin_reg(w,X):#w:2x1 X:nx1 X_new: nx2
    bias_feature=np.ones((X.shape[0], 1))
    X_new = np.concatenate((X, bias_feature), axis=1)
    return np.dot(w,X_new)

def custom_loss_given_weights(w):
    y_predicted = lin_reg(w, X)
    return score4(y_predicted, y)
    
gradient = grad(custom_loss_given_weights)
''' 
def lin_reg(w,X):#w:2x1 X:nx1 X_new: nx2
    bias_feature=np.ones((X.shape[0], 1))
    X_new = np.concatenate((X, bias_feature), axis=1)
    #print("X_new shape:"+str(X_new.shape))
    #print("bias_feature"+str(bias_feature.shape))
    #print("w shape:"+str(w.shape))
    return np.dot(X_new, w)

def custom_loss_given_weights(w):
    y_predicted = lin_reg(w, X)
    #print("within custom loss given wt X:"+str(X))
    return score4(y_predicted, y)
  
gradient = grad(custom_loss_given_weights)


NameError: name 'grad' is not defined

In [58]:
def score4(yhat, y):#yhat is array of demand, y is dataframe of demand act, price act, solar act #(bid, quantity,  demand_act, price_act, solar_act):
    
    bid = np.array(priceKnn24).reshape(-1,1)
    quantity = yhat-np.array(solarKnn24).reshape(-1,1)
    
    demand_act = np.array(y.iloc[:,:24]).reshape(-1,1)
    price_act = np.array(y.iloc[:,24:48]).reshape(-1,1)
    solar_act = np.array(y.iloc[:,48:72]).reshape(-1,1)
    
    #print("yhat:"+str(yhat))
    #print("y:"+str(y))
    #demand_act = demand_act_cv_test
    #price_act = price_act_cv_test
    #solar_act = solar_act_cv_test
    
    battery=0
    excess=0
    paisa=0
    for i in range(0, bid.shape[0]):
        
        #p-quantity we ordered
        #q-how much less we are ordering from actual
        #r-how much is actually required
        p = quantity[i]
        r = demand_act[i]-solar_act[i]
        q = r-p
        #print("q:"+str(q))
        if bid[i]>=price_act[i]: #bid won
            paisa=paisa+p*bid[i]
            if q>0:
                paisa=paisa+(q-min(q,4,battery))*7
                battery=battery-min(q,4,battery)
            else:
                battery=battery+min(-q,5)
                battery=min(battery,25)
        else:#bid lost
            if r>=0:
                paisa=paisa+(r-min(r,4,battery))*7
                battery=battery-min(r,4,battery)
            else:
                battery=battery+min(-r,5)
                battery=min(battery, 25)
                
    #print("battery left: "+str(battery) )
    #print("paisa:"+str(paisa))
    return paisa

In [59]:
def score5(yhat, y):#yhat is array of demand, y is dataframe of demand act, price act, solar act #(bid, quantity,  demand_act, price_act, solar_act):
    
    bid = np.array(priceKnn24).reshape(-1,1)
    quantity = yhat-np.array(solarKnn24).reshape(-1,1)
    
    demand_act = np.array(y.iloc[:,:24]).reshape(-1,1)
    price_act = np.array(y.iloc[:,24:48]).reshape(-1,1)
    solar_act = np.array(y.iloc[:,48:72]).reshape(-1,1)
    
    #print("yhat:"+str(yhat))
    #print("y:"+str(y))
    #demand_act = demand_act_cv_test
    #price_act = price_act_cv_test
    #solar_act = solar_act_cv_test
    bill_act = np.multiply(demand_act-solar_act, price_act)
    bill_ped = np.multiply(quantity, bid)
    
    cost=np.sum(np.sum(np.square(bill_act-bill_ped), axis=1), axis=0)
    return cost
    ''' 
    battery=0
    excess=0
    paisa=0
    for i in range(0, bid.shape[0]):
        
        #p-quantity we ordered
        #q-how much less we are ordering from actual
        #r-how much is actually required
        p = quantity[i]
        r = demand_act[i]-solar_act[i]
        q = r-p
        #print("q:"+str(q))
        if bid[i]>=price_act[i]: #bid won
            paisa=paisa+p*bid[i]
            if q>0:
                paisa=paisa+(q-min(q,4,battery))*7
                battery=battery-min(q,4,battery)
            else:
                battery=battery+min(-q,5)
                battery=min(battery,25)
        else:#bid lost
            if r>=0:
                paisa=paisa+(r-min(r,4,battery))*7
                battery=battery-min(r,4,battery)
            else:
                battery=battery+min(-r,5)
                battery=min(battery, 25)
                
    #print("battery left: "+str(battery) )
    #print("paisa:"+str(paisa))
    return paisa
    ''' 

In [60]:
my_scorer=make_scorer(score4, greater_is_better=False)

In [61]:
demandEN.shape

(2400,)

In [62]:
demand_pred_train.shape

(850, 24)

In [261]:
splits=17
cv = KFold(n_splits=splits, shuffle=True, random_state=1)
scores=0
score=0
scores_array = []
for p_neighbours in [4]:#[3,4,5,6,7,8,9]:
    
    for s_neighbours in [9]:
        
        scores=0
        for traincv, testcv in cv.split(demand_pred_train,demand_act_train):

            price_pred_cv_train = price_pred_train.iloc[traincv]
            price_pred_cv_test  = price_pred_train.iloc[testcv]
            price_act_cv_train  = price_act_train.iloc[traincv]
            price_act_cv_test   = price_act_train.iloc[testcv]

            demand_pred_cv_train = demand_pred_train.iloc[traincv]
            demand_pred_cv_test  = demand_pred_train.iloc[testcv]
            demand_act_cv_train  = demand_act_train.iloc[traincv]
            demand_act_cv_test   = demand_act_train.iloc[testcv]

            solar_pred_cv_train = solar_pred_train.iloc[traincv]
            solar_pred_cv_test  = solar_pred_train.iloc[testcv]
            solar_act_cv_train  = solar_act_train.iloc[traincv]
            solar_act_cv_test   = solar_act_train.iloc[testcv]

            #y = pd.concat((demand_act_cv_test, price_act_cv_test, solar_act_cv_test), axis=1, ignore_index=True)

            #Knn in the house
            #print("train shape:"+str(demand_pred_cv_train.shape))
            #print("test shape:"+str(demand_pred_cv_test.shape))

            estKnn24 = neighbors.KNeighborsRegressor(n_neighbors=p_neighbours, n_jobs=-1)
            estKnn24.fit(price_pred_cv_train, price_act_cv_train)
            priceKnn24 = estKnn24.predict(price_pred_cv_test)+price_std2+0.34 #for cv 0.5 was faound earlier

            estKnn24 = neighbors.KNeighborsRegressor(n_neighbors=s_neighbours, n_jobs=-1)
            estKnn24.fit(solar_pred_cv_train, solar_act_cv_train)
            solarKnn24 = estKnn24.predict(solar_pred_cv_test)+1

            estEN.fit( np.array(demand_pred_cv_train).reshape(-1,1), np.array(demand_act_cv_train).ravel() )
            demandEN = (estEN.predict(np.array(demand_pred_cv_test).reshape(-1,1))).reshape(-1,1)

            y = pd.concat((demand_pred_cv_test, price_pred_cv_test, solar_pred_cv_test), axis=1, ignore_index=True)
            
            score=score4(demandEN, y)
            #print(str(score))
            scores+=score


        print("p_neighbours:"+str(p_neighbours)+" s_neighbours:"+str(s_neighbours))
        print("scores: "+str(scores/splits))
        scores_array.append(scores/splits)

p_neighbours:4 s_neighbours:9
scores: [ 309124.17694396]


In [250]:
price_std2

array([[ 0.08703023,  0.08386974,  0.07924294,  0.08079338,  0.08351364,
         0.11163246,  0.18886007,  0.21889496,  0.24281805,  0.23664099,
         0.20785652,  0.16684295,  0.16782499,  0.15498694,  0.16954093,
         0.15181267,  0.15353714,  0.15996879,  0.17459522,  0.15141513,
         0.14510949,  0.13771801,  0.11646971,  0.07919927]])

In [49]:
scores_array.sort()

In [50]:
scores_array

[array([ 310104.50976735]),
 array([ 310108.14894318]),
 array([ 310118.83304651]),
 array([ 310119.38480531]),
 array([ 310119.55794848]),
 array([ 310126.58176068]),
 array([ 310126.81139382]),
 array([ 310129.55048904]),
 array([ 310232.48313499]),
 array([ 310236.19946574]),
 array([ 310247.18285692]),
 array([ 310247.18833131]),
 array([ 310247.42074169]),
 array([ 310252.41158434]),
 array([ 310254.19398469]),
 array([ 310254.72775218]),
 array([ 310255.89309173]),
 array([ 310257.69635651]),
 array([ 310266.37641922]),
 array([ 310267.43537111]),
 array([ 310267.56124662]),
 array([ 310274.77739088]),
 array([ 310275.18473456]),
 array([ 310277.47938675]),
 array([ 310289.11700421]),
 array([ 310292.82440129]),
 array([ 310302.75190401]),
 array([ 310303.48167824]),
 array([ 310303.84757747]),
 array([ 310310.84365541]),
 array([ 310311.01990607]),
 array([ 310313.66835381]),
 array([ 310350.64036315]),
 array([ 310354.12064117]),
 array([ 310359.85799407]),
 array([ 310363.3099

In [13]:
from autograd import grad

In [283]:
def lin_reg(w,X):#w:2x1 X:nx1 X_new: nx2
    bias_feature=np.ones((X.shape[0], 1))
    X_new = np.concatenate((X, bias_feature), axis=1)
    print("X_new shape:"+str(X_new.shape))
    print("bias_feature"+str(bias_feature.shape))
    print("w shape:"+str(w.shape))
    return np.dot(X_new, w)

def custom_loss_given_weights(w):
    y_predicted = lin_reg(w, X)
    return score4(y_predicted, y)
    
gradient = grad(custom_loss_given_weights)

X = np.array(demand_pred_test).reshape(-1,1)
y = pd.concat((demand_pred_test, price_pred_test, solar_pred_test), axis=1, ignore_index=True)
    
print("X shape:"+str(X.shape))
print("y shape:"+str(y.shape))

weights = np.zeros((X.shape[1]+1,1))

for i in range(10000):
    if i % 1000 == 0:
        print('Iteration %-4d | Loss: %.4f' % (i, custom_loss_given_weights(weights)))
    weights -= gradient(weights) * .01



X shape:(1200, 1)
y shape:(50, 72)
X_new shape:(1200, 2)
bias_feature(1200, 1)
w shape:(2, 1)
Iteration 0    | Loss: 563238.1848
X_new shape:(1200, 2)
bias_feature(1200, 1)
w shape:(2, 1)
X_new shape:(1200, 2)
bias_feature(1200, 1)
w shape:(2, 1)
X_new shape:(1200, 2)
bias_feature(1200, 1)
w shape:(2, 1)
X_new shape:(1200, 2)
bias_feature(1200, 1)
w shape:(2, 1)
X_new shape:(1200, 2)
bias_feature(1200, 1)
w shape:(2, 1)
X_new shape:(1200, 2)
bias_feature(1200, 1)
w shape:(2, 1)
X_new shape:(1200, 2)
bias_feature(1200, 1)
w shape:(2, 1)
X_new shape:(1200, 2)
bias_feature(1200, 1)
w shape:(2, 1)
X_new shape:(1200, 2)
bias_feature(1200, 1)
w shape:(2, 1)
X_new shape:(1200, 2)
bias_feature(1200, 1)
w shape:(2, 1)
X_new shape:(1200, 2)
bias_feature(1200, 1)
w shape:(2, 1)
X_new shape:(1200, 2)
bias_feature(1200, 1)
w shape:(2, 1)
X_new shape:(1200, 2)
bias_feature(1200, 1)
w shape:(2, 1)
X_new shape:(1200, 2)
bias_feature(1200, 1)
w shape:(2, 1)
X_new shape:(1200, 2)
bias_feature(1200, 1)
w

KeyboardInterrupt: 

In [46]:
np.ones((10, 1))

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [40]:
a=np.array([[1,1],[2,4]])
b=np.array([3,3]).reshape(-1,1)

In [41]:
b

array([[3],
       [3]])

In [42]:
a

array([[1, 1],
       [2, 4]])

In [43]:
(np.sum(np.multiply(b,a), axis=1)).shape

(2,)

In [44]:
np.dot(a,b)

array([[ 6],
       [18]])

In [63]:
price_std2=(price_act-price_pred)

In [64]:
price_std2[price_std2<0]=0

In [65]:
price_std2.describe()

0           1           2           3           4           5  \
count  900.000000  900.000000  900.000000  900.000000  900.000000  900.000000   
mean     0.065211    0.059878    0.055989    0.060356    0.063667    0.077611   
std      0.087030    0.083870    0.079243    0.080793    0.083514    0.111632   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.010000    0.000000   
75%      0.120000    0.110000    0.100000    0.120000    0.120000    0.150000   
max      0.330000    0.330000    0.340000    0.340000    0.360000    0.450000   

               6           7           8           9     ...              14  \
count  900.00000  900.000000  900.000000  900.000000     ...      900.000000   
mean     0.14220    0.149889    0.182711    0.174800     ...        0.124622   
std      0.18886    0.218895    0.242818    0.236641     ...        0.169541   
min      0.00000    0.000000    0.000000    0.000000     ...        0.000000   
25%      0.00000    0.000000    0.000000    0.000000     ...        0.000000   
50%      0.01000    0.000000    0.015000    0.010000     ...        0.010000   
75%      0.26000    0.260000    0.340000    0.320000     ...        0.220000   
max      0.72000    0.990000    1.050000    0.990000     ...        0.730000   

               15          16          17          18          19          20  \
count  900.000000  900.000000  900.000000  900.000000  900.000000  900.000000   
mean     0.106622    0.114544    0.123556    0.130967    0.107856    0.108722   
std      0.151813    0.153537    0.159969    0.174595    0.151415    0.145109   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.030000    0.000000    0.000000    0.000000   
75%      0.200000    0.210000    0.230000    0.260000    0.220000    0.210000   
max      0.600000    0.600000    0.660000    0.780000    0.580000    0.540000   

               21          22          23  
count  900.000000  900.000000  900.000000  
mean     0.100700    0.090811    0.057333  
std      0.137718    0.116470    0.079199  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000  
75%      0.190000    0.180000    0.110000  
max      0.560000    0.430000    0.300000  

[8 rows x 24 columns]

In [66]:
price_std2=price_std2.describe().iloc[2,:]

In [67]:
price_std2=np.array(price_std2).reshape(1,-1)

In [68]:
price_std2.shape

(1, 24)

In [69]:
price_std2

array([[ 0.08703023,  0.08386974,  0.07924294,  0.08079338,  0.08351364,
         0.11163246,  0.18886007,  0.21889496,  0.24281805,  0.23664099,
         0.20785652,  0.16684295,  0.16782499,  0.15498694,  0.16954093,
         0.15181267,  0.15353714,  0.15996879,  0.17459522,  0.15141513,
         0.14510949,  0.13771801,  0.11646971,  0.07919927]])

In [122]:
priceslb_bk = np.copy(priceslb)

In [70]:
#submission

In [71]:
price_std=(price_act-price_pred).describe().iloc[2,:]
quantity_std=(demand_act-solar_act-(demand_pred-solar_pred))

In [72]:
price_pred.shape

(900, 24)

In [73]:
#KNN using 24 features at once

estKnn24 = neighbors.KNeighborsRegressor(n_neighbors=7, n_jobs=-1)
estKnn24.fit(demand_pred, demand_act)
demandKnn24 = estKnn24.predict(lb_demand)

estKnn24 = neighbors.KNeighborsRegressor(n_neighbors=4, n_jobs=-1)
estKnn24.fit(price_pred, price_act)
priceKnn24 = estKnn24.predict(lb_price)

estKnn24 = neighbors.KNeighborsRegressor(n_neighbors=9, n_jobs=-1)
estKnn24.fit(solar_pred, solar_act)
solarKnn24 = estKnn24.predict(lb_solar)

print("done4")
#score2(pd.DataFrame(demandKnn24), pd.DataFrame(priceKnn24), pd.DataFrame(solarKnn24), np.concatenate( (demand_act_test,price_act_test,solar_act_test), axis=1) )

done4


In [74]:
type(estEN.coef_)

numpy.ndarray

In [75]:
estEN.coef_

array([ 0.97760076])

In [76]:
estEN.intercept_

1.7105931282868312

In [77]:
#Elasticnet using 1 feature
estEN = linear_model.ElasticNetCV(cv=18)

#est.fit(np.array(demand_pred).reshape(-1,1), np.array(demand_act).ravel())
#scores=cross_val_score(estEN, np.array(demand_pred).reshape(-1,1), np.array(demand_act).ravel() )
#print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
estEN.fit( np.array(demand_pred).reshape(-1,1), np.array(demand_act).ravel() )
#estEN.coef_= np.array([1])
#estEN.intercept_= 1.6376168
demandEN = estEN.predict(np.array(lb_demand).reshape(-1,1))

''' 
#scores=cross_val_score(estEN, np.array(price_pred).reshape(-1,1), np.array(price_act).ravel() )
#print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
estEN.fit( np.array(price_pred).reshape(-1,1), np.array(price_act).ravel())
priceEN = estEN.predict(np.array(lb_price).reshape(-1,1))

#scores=cross_val_score(estEN, np.array(solar_pred).reshape(-1,1), np.array(solar_act).ravel() )
#print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
estEN.fit( np.array(solar_pred).reshape(-1,1), np.array(solar_act).ravel()) 
solarEN = estEN.predict(np.array(lb_solar).reshape(-1,1))
''' 
print("done3")
#print(str(pd.DataFrame(demandEN).shape)+"s ")

#score3(pd.DataFrame(demandEN.reshape(50,24)), pd.DataFrame(priceEN.reshape(50,24)), pd.DataFrame(solarEN.reshape(50,24)), (demand_act_test), (price_act_test), (solar_act_test) )

done3


In [ ]:
0.96734275],[ 1.63682223]
0.96745217],[ 1.63512839
        
1.02092761],[ 1.64126239
 0.99368733],[ 1.6376168

In [97]:
battery1200 = pd.read_csv('battery2400.csv', header=None)

In [98]:
battery1200.shape

(2400, 1)

In [80]:
demandslb = np.array([demandEN.reshape(100,24)])
priceslb = np.array([priceKnn24])
solarslb = np.array([solarKnn24])


In [81]:
# i-demand
#j-price
#k-solar
i=0
j=0
k=0

In [82]:
a=0.15 #on cv 0.5 worked
b=-1

In [83]:
priceslbx=[]
priceslbx=np.copy(priceslb[j])

In [84]:
priceslbx[:,0].shape

(100,)

In [85]:
np.sum(np.nan_to_num(np.multiply(demandslb[i][priceslbx>7], (priceslbx[priceslbx>7]-7) ) ) )

216.14545666154754

In [86]:
priceslbx

array([[ 1.21  ,  1.195 ,  1.105 , ...,  3.065 ,  2.335 ,  1.405 ],
       [ 1.7825,  1.7025,  1.655 , ...,  2.73  ,  2.0275,  1.6875],
       [ 1.3425,  1.3575,  1.3575, ...,  3.22  ,  2.1525,  1.345 ],
       ..., 
       [ 1.3125,  1.3225,  1.3125, ...,  2.33  ,  2.0625,  1.82  ],
       [ 1.8125,  1.705 ,  1.6425, ...,  2.615 ,  2.33  ,  1.815 ],
       [ 1.9175,  1.785 ,  1.6725, ...,  2.5   ,  2.535 ,  2.11  ]])

In [87]:
priceslbx=priceslbx+price_std2+0.34 #based on cv
priceslbx[priceslbx>=7]=6.85

#priceslbx[priceslbx>=7]=6.3
#priceslbx=priceslbx+a
#priceslbx[priceslbx>=7]=6.85

In [88]:
priceslbx

array([[ 1.63703023,  1.61886974,  1.52424294, ...,  3.54271801,
         2.79146971,  1.82419927],
       [ 2.20953023,  2.12636974,  2.07424294, ...,  3.20771801,
         2.48396971,  2.10669927],
       [ 1.76953023,  1.78136974,  1.77674294, ...,  3.69771801,
         2.60896971,  1.76419927],
       ..., 
       [ 1.73953023,  1.74636974,  1.73174294, ...,  2.80771801,
         2.51896971,  2.23919927],
       [ 2.23953023,  2.12886974,  2.06174294, ...,  3.09271801,
         2.78646971,  2.23419927],
       [ 2.34453023,  2.20886974,  2.09174294, ...,  2.97771801,
         2.99146971,  2.52919927]])

In [89]:
submission = np.concatenate( ( (priceslbx).reshape(-1,1), demandslb[i].reshape(-1,1)-solarslb[k].reshape(-1,1)+b)  , axis=1 )

In [90]:
submission.shape

(2400, 2)

In [91]:
submissiondf = pd.DataFrame(submission)

In [99]:
submissiondf.to_csv('24.csv', index=False, index_label=False, header=None)

In [93]:
fuck=np.array(lb_price).reshape(-1,1)

In [94]:
fuck[-5:]

array([[ 3.04],
       [ 2.56],
       [ 2.74],
       [ 2.34],
       [ 1.87]])

In [42]:
price_std2

array([[ 0.08703023,  0.08386974,  0.07924294,  0.08079338,  0.08351364,
         0.11163246,  0.18886007,  0.21889496,  0.24281805,  0.23664099,
         0.20785652,  0.16684295,  0.16782499,  0.15498694,  0.16954093,
         0.15181267,  0.15353714,  0.15996879,  0.17459522,  0.15141513,
         0.14510949,  0.13771801,  0.11646971,  0.07919927]])

In [39]:
submissiondf = pd.read_csv('24.csv', header=None)
submissiondf

0           1
0     2.230292   31.211737
1     1.916998   29.901752
2     1.878616   25.805605
3     1.854739   67.783782
4     2.014387   19.441424
5     2.311096   21.308641
6     2.656870   47.567112
7     3.252264  129.514974
8     3.737320   70.192507
9     3.670969   11.442439
10    3.293147    3.528940
11    3.100604   68.780889
12    3.168244  123.498179
13    3.071278   75.064702
14    3.011811   80.658460
15    2.793833   51.749182
16    2.924796   88.034960
17    2.895767   19.943027
18    2.961544   36.422349
19    2.745896   74.763851
20    3.080204   51.330761
21    2.725723  144.222385
22    2.571421   34.633340
23    2.148212   54.302667
24    2.023149   20.624321
25    1.686998   55.505116
26    1.445759   18.708223
27    1.433311   54.801243
28    1.435815   23.273619
29    2.883953   28.474455
...        ...         ...
1170  3.388687  133.537209
1171  3.147324  101.442576
1172  3.054489  156.227323
1173  3.040008  105.626707
1174  2.544278   27.418646
1175  1.493927   23.918835
1176  1.388864   19.979104
1177  1.375570   15.980717
1178  1.398616   17.857711
1179  1.377596   17.495998
1180  1.388672   22.286242
1181  2.363953   58.496574
1182  3.385442   59.775076
1183  3.799407  163.545839
1184  3.757320   89.569116
1185  3.878112   62.244816
1186  3.560290   22.648670
1187  2.647747   49.062691
1188  2.446816   13.173763
1189  2.398421    3.380234
1190  2.461811    2.257611
1191  2.749547   10.803833
1192  2.669082   25.793569
1193  2.715767   92.438878
1194  3.352973  120.192958
1195  3.150182  143.010160
1196  3.004489   97.141132
1197  2.768580   83.816434
1198  2.504278   76.914573
1199  1.471070   61.155648

[1200 rows x 2 columns]

In [100]:
charged=0
discharged=0
#a-charge by, b-discharge by  1.5 1
a=1.5
b=1
submissiondf = pd.read_csv('24.csv', header=None)

for c in range(len(battery1200)):
    if battery1200.iloc[c,0]==1:
        print("chege"+str(submissiondf.iloc[c,0]))
        submissiondf.iloc[c,1] = submissiondf.iloc[c,1] + a
        charged=charged+1
        continue
    if battery1200.iloc[c,0]==2 :
        print("discharge:"+str(submissiondf.iloc[c,0]))
        submissiondf.iloc[c,1] = submissiondf.iloc[c,1] - b
        discharged=discharged+1
        continue
submissiondf.to_csv('private_15.csv', index=False, index_label=False, header=None)

chege1.63703022559
chege1.61886974484
chege1.52424294103
chege1.4007933839
chege1.88601363513
discharge:4.23886006614
discharge:5.80389496186
discharge:5.87031805144
discharge:5.15664099147
chege4.36035652192
discharge:4.56184294867
discharge:4.70032498896
chege4.0820409347
discharge:4.076812672
chege4.05603713584
discharge:4.06709522232
chege3.40510948862
discharge:3.54271801
chege1.82419927416
chege2.20953022559
chege2.12636974484
chege2.07424294103
chege2.1057933839
discharge:2.18351363513
chege2.25663246091
discharge:4.12136006614
discharge:5.72889496186
discharge:5.29281805144
discharge:5.01914099147
discharge:4.04285652192
chege3.75434294867
discharge:4.00032498896
chege3.07748694193
discharge:3.159312672
chege3.09603713584
chege2.90246878944
chege3.11459522232
discharge:3.11641513121
discharge:3.70010948862
discharge:3.20771801
chege2.10669927416
chege1.76953022559
chege1.77674294103
chege1.7707933839
chege1.80601363513
discharge:3.91389496186
discharge:3.29914099147
discharge:3

discharge:3.86010948862
chege2.99646970556
chege2.60419927416
chege2.43203022559
chege2.44886974484
chege2.45424294103
discharge:5.01636006614
discharge:5.61139496186
discharge:6.18281805144
discharge:5.70664099147
chege5.09285652192
discharge:4.38934294867
chege4.15282498896
chege4.4970409347
discharge:4.419312672
discharge:4.45603713584
discharge:5.41959522232
chege4.28391513121
discharge:3.83510948862
chege2.23453022559
chege2.33386974484
chege2.31924294103
chege2.2332933839
chege2.22851363513
discharge:5.00636006614
discharge:5.76639496186
discharge:6.00781805144
discharge:6.85
discharge:5.02684294867
chege4.56248694193
chege4.6045409347
chege4.049312672
discharge:4.13353713584
discharge:4.36246878944
discharge:4.54709522232
chege2.13419927416
chege2.14636974484
chege2.08174294103
chege2.0332933839
chege2.10851363513
discharge:3.79889496186
chege3.98281805144
discharge:4.13664099147
discharge:4.16035652192
discharge:3.57684294867
discharge:3.67032498896
discharge:3.41498694193
cheg

discharge:4.11889496186
discharge:4.13281805144
discharge:4.14414099147
discharge:3.34285652192
chege2.99434294867
chege3.00248694193
discharge:3.0145409347
discharge:2.651812672
chege2.84496878944
discharge:3.11141513121
chege3.01010948862
discharge:2.83521801
chege2.50146970556
chege2.24669927416
chege2.24953022559
chege2.13636974484
chege2.0732933839
discharge:3.87886006614
discharge:4.07889496186
discharge:4.07281805144
chege3.22914099147
chege2.87285652192
chege3.45684294867
discharge:3.44282498896
discharge:3.40248694193
discharge:3.4045409347
chege1.646812672
chege2.12353713584
chege2.98496878944
discharge:3.23209522232
discharge:3.33641513121
chege3.31010948862
chege3.11521801
discharge:2.79896970556
chege2.24169927416
discharge:2.40453022559
discharge:2.20636974484
chege2.07424294103
chege2.0907933839
discharge:3.42639496186
discharge:3.98031805144
discharge:3.45914099147
chege3.15035652192
discharge:3.22434294867
discharge:3.58532498896
discharge:3.39248694193
chege3.34704093

discharge:3.02103713584
discharge:3.15746878944
discharge:3.35709522232
chege3.12391513121
discharge:3.31260948862
chege2.16203022559
chege2.07136974484
chege1.85424294103
chege1.7757933839
chege2.02601363513
discharge:3.25889496186
discharge:3.36781805144
discharge:3.39414099147
discharge:3.17035652192
discharge:2.85684294867
chege1.7745409347
chege1.301812672
discharge:2.46603713584
discharge:2.52746878944
chege2.43709522232
discharge:2.44641513121
chege1.98771801
chege1.78896970556
chege1.75919927416
chege1.73953022559
discharge:1.74636974484
chege1.73174294103
chege1.7307933839
discharge:4.09639496186
discharge:4.10031805144
discharge:4.10164099147
discharge:3.32285652192
chege3.00184294867
discharge:2.99032498896
discharge:2.99998694193
chege3.0095409347
chege2.626812672
discharge:2.75853713584
chege2.85246878944
discharge:3.11459522232
chege3.12641513121
discharge:3.00510948862
discharge:2.80771801
chege2.23919927416
chege2.12886974484
chege2.06174294103
chege2.0507933839
chege2.

In [668]:
charged

467

In [1045]:
submissiondf

0           1
0     2.301429   31.211737
1     1.991429   29.901752
2     1.957143   25.805605
3     1.934286   67.783782
4     2.090000   19.441424
5     2.362857   21.308641
6     2.641429   47.567112
7     3.211429  129.514974
8     3.677143   70.192507
9     3.610000   11.442439
10    3.265714    3.528940
11    3.101429   68.780889
12    3.170000  123.498179
13    3.084286   75.064702
14    3.021429   80.658460
15    2.811429   51.749182
16    2.941429   88.034960
17    2.905714   19.943027
18    2.958571   36.422349
19    2.762857   74.763851
20    3.101429   51.330761
21    2.757143  144.222385
22    2.618571   34.633340
23    2.227143   54.302667
24    2.094286   20.624321
25    1.761429   55.505116
26    1.524286   18.708223
27    1.512857   54.801243
28    1.511429   23.273619
29    2.935714   28.474455
...        ...         ...
1170  3.385714  133.537209
1171  3.164286  101.442576
1172  3.075714  156.227323
1173  3.071429  105.626707
1174  2.591429   27.418646
1175  1.572857   23.918835
1176  1.460000   19.979104
1177  1.450000   15.980717
1178  1.477143   17.857711
1179  1.457143   17.495998
1180  1.464286   22.286242
1181  2.415714   58.496574
1182  3.370000   59.775076
1183  3.758571  163.545839
1184  3.697143   89.569116
1185  3.817143   62.244816
1186  3.532857   22.648670
1187  2.648571   49.062691
1188  2.448571   13.173763
1189  2.411429    3.380234
1190  2.471429    2.257611
1191  2.767143   10.803833
1192  2.685714   25.793569
1193  2.725714   92.438878
1194  3.350000  120.192958
1195  3.167143  143.010160
1196  3.025714   97.141132
1197  2.800000   83.816434
1198  2.551429   76.914573
1199  1.550000   61.155648

[1200 rows x 2 columns]

In [669]:
1200-467*2

266

In [671]:
submissiondf.shape

(1200, 2)

In [672]:
submissiondf.to_csv('23.csv', index=False, index_label=False)

In [123]:
submissiondf.iloc[:,0].shape

(1200,)